# Generated by Django 2.1.7 on 2019-03-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('1', 'IOS'), ('2', 'ANDROID')], max_length=1)),
                ('app_version', models.CharField(max_length=10)),
                ('app_link', models.TextField()),
                ('optional_update', models.BooleanField(default=True)),
            ],
        ),
    ]
